version: "3"
services:
    springapp:
      build: .
      container_name: library
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      ports:
        - 8081:8080
      restart: always
      depends_on:
        - db
    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=postgres
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5432:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: always
volumes:
    pgdata: